version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: sudo apt-get update; sudo apt-get install ruby-sass
      - run: npm install
      - run: sudo npm install webpack-cli -g
      - run: sudo npm install webpack -g
      - run: webpack
      - run: echo "DONE!"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master